# 数据拼接 concat

In [1]:
import numpy as np
import pandas as pd

* NumPy的concat

In [2]:
arr1 = np.random.randint(0, 10, (3, 4))
arr2 = np.random.randint(0, 10, (3, 4))

print(arr1)
print(arr2)

[[8 5 3 3]
 [7 9 4 0]
 [9 2 7 3]]
[[9 1 8 3]
 [1 1 7 7]
 [9 7 0 4]]


In [3]:
# 默认的是上下拼接
np.concatenate([arr1, arr2])

array([[8, 5, 3, 3],
       [7, 9, 4, 0],
       [9, 2, 7, 3],
       [9, 1, 8, 3],
       [1, 1, 7, 7],
       [9, 7, 0, 4]])

In [4]:
np.concatenate([arr1, arr2], axis=1)

array([[8, 5, 3, 3, 9, 1, 8, 3],
       [7, 9, 4, 0, 1, 1, 7, 7],
       [9, 2, 7, 3, 9, 7, 0, 4]])

* Series上的concat

In [5]:
# index 没有重复的情况
ser1 = pd.Series(np.random.randint(0, 10, 5), index=range(0,5))
ser2 = pd.Series(np.random.randint(0, 10, 4), index=range(5,9))
ser3 = pd.Series(np.random.randint(0, 10, 3), index=range(9,12))

print(ser1)
print(ser2)
print(ser3)

0    5
1    6
2    9
3    8
4    6
dtype: int32
5    0
6    1
7    1
8    4
dtype: int32
9     0
10    4
11    4
dtype: int32


In [8]:
pd.concat([ser1, ser2, ser3])  # 默认的是上下拼接

0     8
1     8
2     7
3     3
4     5
5     0
6     6
7     4
8     2
9     2
10    6
11    1
dtype: int32

In [9]:
pd.concat([ser1, ser2, ser3], axis=1)   # 左右拼接，拼接的时候如果没有对应元素进行以空值填充

0    1    2
0   8.0  NaN  NaN
1   8.0  NaN  NaN
2   7.0  NaN  NaN
3   3.0  NaN  NaN
4   5.0  NaN  NaN
5   NaN  0.0  NaN
6   NaN  6.0  NaN
7   NaN  4.0  NaN
8   NaN  2.0  NaN
9   NaN  NaN  2.0
10  NaN  NaN  6.0
11  NaN  NaN  1.0

In [6]:
# index 有重复的情况
ser1 = pd.Series(np.random.randint(0, 10, 5), index=range(5))
ser2 = pd.Series(np.random.randint(0, 10, 4), index=range(4))
ser3 = pd.Series(np.random.randint(0, 10, 3), index=range(3))

print(ser1)
print(ser2)
print(ser3)

0    4
1    6
2    9
3    3
4    9
dtype: int32
0    7
1    3
2    5
3    3
dtype: int32
0    6
1    1
2    5
dtype: int32


In [9]:
# 上下拼接可以无视索引
pd.concat([ser1, ser2, ser3])  #  默认不考虑重复索引

0    4
1    6
2    9
3    3
4    9
0    7
1    3
2    5
3    3
0    6
1    1
2    5
dtype: int32

In [10]:
pd.concat([ser1, ser2, ser3], axis=1)   # 左右拼接是考虑索引

0    1    2
0  4  7.0  6.0
1  6  3.0  1.0
2  9  5.0  5.0
3  3  3.0  NaN
4  9  NaN  NaN

In [11]:
pd.concat([ser1, ser2, ser3], axis=1, join='outer')

0  1  2
0  4  7  6
1  6  3  1
2  9  5  5

* DataFrame上的concat

In [12]:
df1 = pd.DataFrame(np.random.randint(0, 10, (3, 2)), index=['a', 'b', 'c'],
                       columns=['A', 'B'])
df2 = pd.DataFrame(np.random.randint(0, 10, (2, 2)), index=['a', 'b'],
                       columns=['C', 'D'])
print(df1)
print(df2)

   A  B
a  9  8
b  9  9
c  2  4
   C  D
a  7  4
b  6  6


In [16]:
pd.concat([df1, df2])   # 默认是上下拼接

A    B    C    D
a  9.0  8.0  NaN  NaN
b  9.0  9.0  NaN  NaN
c  2.0  4.0  NaN  NaN
a  NaN  NaN  7.0  4.0
b  NaN  NaN  6.0  6.0

In [15]:
pd.concat([df1, df2], axis=1)

A  B    C    D
a  9  8  7.0  4.0
b  9  9  6.0  6.0
c  2  4  NaN  NaN